# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GITSNetwork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.8.1'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :tag => '4.2.0'
  pod 'ReachabilitySwift'
end
